---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    proxmox_cluster:
      hosts:
        cdx-pve-01:
        cdx-pve-02:
        cdx-pve-03:
      vars:
        ansible_user: root
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
