version: '3.8'

# CDX-DNS Stack - Docker Host 3 (Asia-Pacific)
# Geographic Region: EQIX10 Seoul
# Containers: 2 total (1 root + 1 control/monitoring)
# Extract location: /opt/docker-stacks/cdx-dns/bind/
# Archive: cdx-dns-bind-docker-3-GEOGRAPHIC.tar.gz

services:
  #
  # EQIX10 Seoul Root Server (1 container)
  #

  m.root-servers.net:
    image: ubuntu/bind9:latest
    container_name: m.root-servers.net
    hostname: m.root-servers.net
    networks:
      eqix10:
        ipv4_address: 202.12.27.33
    volumes:
      - /opt/docker-stacks/cdx-dns/bind/root-zone/db.root:/etc/bind/db.root:ro
      - /opt/docker-stacks/cdx-dns/bind/m-root/named.conf.local:/etc/bind/named.conf.local:ro
      - /opt/docker-stacks/cdx-dns/bind/m-root/named.conf.options:/etc/bind/named.conf.options:ro
      - /opt/docker-stacks/cdx-dns/bind/m-root/db.empty:/etc/bind/db.empty:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1

  #
  # Control/Monitoring Container (1 container)
  #

  cdx-dns-control:
    image: alpine:latest
    container_name: cdx-dns-control
    hostname: cdx-dns-control.cdx.lab
    command: /bin/sh -c "apk add --no-cache bind-tools curl && while true; do sleep 3600; done"
    networks:
      eqix10:
        ipv4_address: 202.12.27.100
    environment:
      - TZ=Asia/Seoul
      - DNS_MONITORING_ENABLED=true
      - DNS_ROOT_SERVERS=198.41.0.4,199.9.14.201,192.33.4.12,199.7.91.13,192.203.230.10,192.5.5.241,192.112.36.4,198.97.190.53,192.36.148.17,192.58.128.30,193.0.14.129,199.7.83.42,202.12.27.33
      - DNS_TLD_PRIMARIES=192.5.5.50,192.5.5.51,192.5.5.52,192.5.5.53,192.5.5.54,192.5.5.55,192.5.5.56,192.5.5.57
    restart: unless-stopped
    labels:
      - "cdx.component=dns-monitoring"
      - "cdx.region=asia-pacific"
      - "cdx.function=control"

#
# Docker Networks
#

networks:
  eqix10:
    driver: macvlan
    driver_opts:
      parent: eth10
    ipam:
      driver: default
      config:
        - subnet: 202.12.27.0/24
          gateway: 202.12.27.1
