version: '3.8'

services:
  
  #
  # London NTP Server (EQIX1)
  #

  cdx-ntp-london:
    image: cturra/ntp:latest
    container_name: ntp-london.cdx.lab
    hostname: ntp-london.cdx.lab
    networks:
      eqix1:
        ipv4_address: 46.33.28.107
    environment:
      - TZ=Europe/London
      - NTP_SERVERS=103.140.210.1
      - LOG_LEVEL=1
    restart: unless-stopped
    cap_add:
      - SYS_TIME
      - SYS_NICE
    labels:
      - "cdx.component=ntp"
      - "cdx.region=europe"
      - "cdx.site=eqix1-london"
      - "cdx.stratum=2"
      - "cdx.dns-entry=eqix1-london"
      - "cdx.critical=true"
      
  #
  # Frankfurt NTP Server (EQIX6)
  # ⭐ PRIMARY - ntp.nist.gov (46.244.164.88)
  #

  cdx-ntp-frankfurt:
    image: cturra/ntp:latest
    container_name: ntp-frankfurt.cdx.lab
    hostname: ntp-frankfurt.cdx.lab
    networks:
      eqix6:
        ipv4_address: 46.244.164.88
    environment:
      - TZ=Europe/Berlin
      - NTP_SERVERS=103.140.210.1
      - LOG_LEVEL=1
    restart: unless-stopped
    cap_add:
      - SYS_TIME
      - SYS_NICE
    labels:
      - "cdx.component=ntp"
      - "cdx.region=europe"
      - "cdx.site=eqix6-frankfurt"
      - "cdx.stratum=2"
      - "cdx.dns-entry=ntp.nist.gov"
      - "cdx.critical=true"

  #
  # Amsterdam NTP Server (EQIX2)
  #

  cdx-ntp-amsterdam:
    image: cturra/ntp:latest
    container_name: ntp-amsterdam.cdx.lab
    hostname: ntp-amsterdam.cdx.lab
    networks:
      eqix2:
        ipv4_address: 37.74.100.100
    environment:
      - TZ=Europe/Amsterdam
      - NTP_SERVERS=103.140.210.1
      - LOG_LEVEL=1
    restart: unless-stopped
    cap_add:
      - SYS_TIME
      - SYS_NICE
    labels:
      - "cdx.component=ntp"
      - "cdx.region=europe"
      - "cdx.site=eqix2-amsterdam"
      - "cdx.stratum=2"
      
networks:
  # ═══════════════════════════════════════════════════════════
  # EQIX1 - London (Area 1)
  # Router: IXP-T1-EQIX-1
  # Parent Interface: eth1
  # ═══════════════════════════════════════════════════════════
  
  eqix1:
    driver: macvlan
    driver_opts:
      parent: eth1
    ipam:
      config:
        # London regional ISP blocks
        - subnet: 46.33.28.0/22
          gateway: 46.33.28.94
        - subnet: 46.33.128.0/19
          gateway: 46.33.128.36
        - subnet: 131.227.0.0/16
          gateway: 131.227.0.124
        - subnet: 91.221.76.0/23
          gateway: 91.221.76.88
        - subnet: 154.58.200.0/21
          gateway: 154.58.200.93
        - subnet: 212.18.160.0/19
          gateway: 212.18.160.204
        - subnet: 62.130.142.0/23
          gateway: 62.130.142.37
        - subnet: 31.187.32.0/19
          gateway: 31.187.32.77
        - subnet: 57.94.0.0/19
          gateway: 57.94.0.99
        - subnet: 5.62.8.0/22
          gateway: 5.62.8.51
        - subnet: 5.153.64.0/19
          gateway: 5.153.64.119
        - subnet: 37.64.0.0/14
          gateway: 37.64.0.25
        - subnet: 2.6.0.0/19
          gateway: 2.6.0.67
        - subnet: 23.222.224.0/20
          gateway: 23.222.224.202
        - subnet: 41.250.224.0/21
          gateway: 41.250.224.44
        - subnet: 62.57.136.0/21
          gateway: 62.57.136.194
        - subnet: 62.106.64.0/19
          gateway: 62.106.64.105
        - subnet: 41.77.176.0/22
          gateway: 41.77.176.116
        - subnet: 41.229.158.0/23
          gateway: 41.229.158.73
        - subnet: 37.102.0.0/18
          gateway: 37.102.0.93
        - subnet: 50.220.138.0/23
          gateway: 50.220.138.191
        
        # Root DNS (London allocation: j, k)
        - subnet: 193.0.14.0/24
          gateway: 193.0.14.1
        - subnet: 192.58.128.0/24
          gateway: 192.58.128.1

  # ═══════════════════════════════════════════════════════════
  # EQIX2 - Amsterdam (Area 2)
  # Router: IXP-T1-EQIX-2
  # Parent Interface: eth2
  # ═══════════════════════════════════════════════════════════
  
  eqix2:
    driver: macvlan
    driver_opts:
      parent: eth2
    ipam:
      config:
        # Amsterdam regional ISP blocks
        - subnet: 62.125.32.0/19
          gateway: 62.125.32.119
        - subnet: 2.16.4.0/23
          gateway: 2.16.4.55
        - subnet: 17.70.0.0/15
          gateway: 17.70.0.72
        - subnet: 46.132.0.0/17
          gateway: 46.132.0.89
        - subnet: 46.132.192.0/18
          gateway: 46.132.192.17
        - subnet: 57.86.128.0/17
          gateway: 57.86.128.73
        - subnet: 62.247.0.0/16
          gateway: 62.247.0.44
        - subnet: 23.78.32.0/19
          gateway: 23.78.32.178
        - subnet: 44.144.0.0/17
          gateway: 44.144.0.102
        - subnet: 31.160.0.0/17
          gateway: 31.160.0.173
        - subnet: 62.213.192.0/21
          gateway: 62.213.192.96
        - subnet: 62.209.0.0/17
          gateway: 62.209.0.52
        - subnet: 57.67.224.0/19
          gateway: 57.67.224.14
        - subnet: 62.59.128.0/20
          gateway: 62.59.128.99
        - subnet: 31.204.128.0/20
          gateway: 31.204.128.67
        - subnet: 62.242.0.0/19
          gateway: 62.242.0.50
        
        # DNS TLD (mrvl)
        - subnet: 198.41.0.0/24
          gateway: 198.41.0.1
        
        # Stark Industries Amsterdam operations
        - subnet: 37.74.0.0/16
          gateway: 37.74.0.87
        
        - subnet: 5.23.56.0/21
          gateway: 5.23.56.21
        - subnet: 31.47.64.0/21
          gateway: 31.47.64.45
        - subnet: 44.161.204.0/23
          gateway: 44.161.204.29
        - subnet: 46.151.96.0/21
          gateway: 46.151.96.58

  # ═══════════════════════════════════════════════════════════
  # EQIX6 - Frankfurt (Area 6)
  # Router: IXP-T1-EQIX-6
  # Parent Interface: eth6
  # ═══════════════════════════════════════════════════════════
  
  eqix6:
    driver: macvlan
    driver_opts:
      parent: eth6
    ipam:
      config:
        # Frankfurt regional ISP blocks
        - subnet: 18.194.0.0/15
          gateway: 18.194.0.22
        
        # NIST NTP service
        - subnet: 46.244.164.0/22
          gateway: 46.244.164.91
        
        # African regional blocks
        - subnet: 41.58.0.0/18
          gateway: 41.58.0.111
        - subnet: 41.243.192.0/18
          gateway: 41.243.192.67
        - subnet: 41.195.0.0/16
          gateway: 41.195.0.29
        - subnet: 41.24.224.0/19
          gateway: 41.24.224.49
        - subnet: 41.72.160.0/19
          gateway: 41.72.160.107
        - subnet: 37.220.192.0/18
          gateway: 37.220.192.88
        
        # Root DNS (Frankfurt allocation: i, m)
        - subnet: 192.36.148.0/24
          gateway: 192.36.148.1
        - subnet: 202.12.27.0/24
          gateway: 202.12.27.1


